#!/bin/bash

# @describe Setup development environment with Nix
# @flag --no-root     Use nix-portable instead of root installation
# @flag --sudo-mount  Use sudo with nsenter/mount for /nix access
# @option --system <SYSTEM>  Target system for cross-compilation (e.g., aarch64-linux, x86_64-linux)
# @arg nix_args~      Additional arguments to pass to nix build

# ARGC-BUILD {
# This block was generated by argc (https://github.com/sigoden/argc).
# Modifying it manually is not recommended

_argc_run() {
    if [[ "${1:-}" == "___internal___" ]]; then
        _argc_die "error: unsupported ___internal___ command"
    fi
    if [[ "${OS:-}" == "Windows_NT" ]] && [[ -n "${MSYSTEM:-}" ]]; then
        set -o igncr
    fi
    argc__args=("$(basename "$0" .sh)" "$@")
    argc__positionals=()
    _argc_index=1
    _argc_len="${#argc__args[@]}"
    _argc_tools=()
    _argc_parse
    if [ -n "${argc__fn:-}" ]; then
        $argc__fn "${argc__positionals[@]}"
    fi
}

_argc_usage() {
    cat <<-'EOF'
Setup development environment with Nix

USAGE: setup [OPTIONS] [NIX-ARGS]...

ARGS:
  [NIX-ARGS]...  Additional arguments to pass to nix build

OPTIONS:
      --no-root          Use nix-portable instead of root installation
      --sudo-mount       Use sudo with nsenter/mount for /nix access
      --system <SYSTEM>  Target system for cross-compilation (e.g., aarch64-linux, x86_64-linux)
  -h, --help             Print help
  -V, --version          Print version
EOF
    exit
}

_argc_version() {
    echo setup 0.0.0
    exit
}

_argc_parse() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage
            ;;
        --version | -version | -V)
            _argc_version
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        --no-root)
            if [[ "$_argc_item" == *=* ]]; then
                _argc_die "error: flag \`--no-root\` don't accept any value"
            fi
            _argc_index=$((_argc_index + 1))
            if [[ -n "${argc_no_root:-}" ]]; then
                _argc_die "error: the argument \`--no-root\` cannot be used multiple times"
            else
                argc_no_root=1
            fi
            ;;
        --sudo-mount)
            if [[ "$_argc_item" == *=* ]]; then
                _argc_die "error: flag \`--sudo-mount\` don't accept any value"
            fi
            _argc_index=$((_argc_index + 1))
            if [[ -n "${argc_sudo_mount:-}" ]]; then
                _argc_die "error: the argument \`--sudo-mount\` cannot be used multiple times"
            else
                argc_sudo_mount=1
            fi
            ;;
        --system)
            _argc_take_args "--system <SYSTEM>" 1 1 "-" ""
            _argc_index=$((_argc_index + _argc_take_args_len + 1))
            if [[ -z "${argc_system:-}" ]]; then
                argc_system="${_argc_take_args_values[0]:-}"
            else
                _argc_die "error: the argument \`--system\` cannot be used multiple times"
            fi
            ;;
        *)
            if _argc_maybe_flag_option "-" "$_argc_item"; then
                _argc_die "error: unexpected argument \`$_argc_key\` found"
            fi
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            if [[ "${#argc__positionals[@]}" -ge 0 ]]; then
                argc__positionals+=("${argc__args[@]:_argc_index}")
                _argc_index=$_argc_len
            fi
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage
        fi
        _argc_match_positionals 1
        local values_index values_size
        IFS=: read -r values_index values_size <<<"${_argc_match_positionals_values[0]:-}"
        if [[ -n "$values_index" ]]; then
            argc_nix_args=("${argc__positionals[@]:values_index:values_size}")
        fi
    fi
}

_argc_take_args() {
    _argc_take_args_values=()
    _argc_take_args_len=0
    local param="$1" min="$2" max="$3" signs="$4" delimiter="$5"
    if [[ "$min" -eq 0 ]] && [[ "$max" -eq 0 ]]; then
        return
    fi
    local _argc_take_index=$((_argc_index + 1)) _argc_take_value
    if [[ "$_argc_item" == *=* ]]; then
        _argc_take_args_values=("${_argc_item##*=}")
    else
        while [[ $_argc_take_index -lt $_argc_len ]]; do
            _argc_take_value="${argc__args[_argc_take_index]}"
            if _argc_maybe_flag_option "$signs" "$_argc_take_value"; then
                if [[ "${#_argc_take_value}" -gt 1 ]]; then
                    break
                fi
            fi
            _argc_take_args_values+=("$_argc_take_value")
            _argc_take_args_len=$((_argc_take_args_len + 1))
            if [[ "$_argc_take_args_len" -ge "$max" ]]; then
                break
            fi
            _argc_take_index=$((_argc_take_index + 1))
        done
    fi
    if [[ "${#_argc_take_args_values[@]}" -lt "$min" ]]; then
        _argc_die "error: incorrect number of values for \`$param\`"
    fi
    if [[ -n "$delimiter" ]] && [[ "${#_argc_take_args_values[@]}" -gt 0 ]]; then
        local item values arr=()
        for item in "${_argc_take_args_values[@]}"; do
            IFS="$delimiter" read -r -a values <<<"$item"
            arr+=("${values[@]}")
        done
        _argc_take_args_values=("${arr[@]}")
    fi
}

_argc_match_positionals() {
    _argc_match_positionals_values=()
    _argc_match_positionals_len=0
    local params=("$@")
    local args_len="${#argc__positionals[@]}"
    if [[ $args_len -eq 0 ]]; then
        return
    fi
    local params_len=$# arg_index=0 param_index=0
    while [[ $param_index -lt $params_len && $arg_index -lt $args_len ]]; do
        local takes=0
        if [[ "${params[param_index]}" -eq 1 ]]; then
            if [[ $param_index -eq 0 ]] &&
                [[ ${_argc_dash:-} -gt 0 ]] &&
                [[ $params_len -eq 2 ]] &&
                [[ "${params[$((param_index + 1))]}" -eq 1 ]] \
                ; then
                takes=${_argc_dash:-}
            else
                local arg_diff=$((args_len - arg_index)) param_diff=$((params_len - param_index))
                if [[ $arg_diff -gt $param_diff ]]; then
                    takes=$((arg_diff - param_diff + 1))
                else
                    takes=1
                fi
            fi
        else
            takes=1
        fi
        _argc_match_positionals_values+=("$arg_index:$takes")
        arg_index=$((arg_index + takes))
        param_index=$((param_index + 1))
    done
    if [[ $arg_index -lt $args_len ]]; then
        _argc_match_positionals_values+=("$arg_index:$((args_len - arg_index))")
    fi
    _argc_match_positionals_len=${#_argc_match_positionals_values[@]}
    if [[ $params_len -gt 0 ]] && [[ $_argc_match_positionals_len -gt $params_len ]]; then
        local index="${_argc_match_positionals_values[params_len]%%:*}"
        _argc_die "error: unexpected argument \`${argc__positionals[index]}\` found"
    fi
}

_argc_maybe_flag_option() {
    local signs="$1" arg="$2"
    if [[ -z "$signs" ]]; then
        return 1
    fi
    local cond=false
    if [[ "$signs" == *"+"* ]]; then
        if [[ "$arg" =~ ^\+[^+].* ]]; then
            cond=true
        fi
    elif [[ "$arg" == -* ]]; then
        if (( ${#arg} < 3 )) || [[ ! "$arg" =~ ^---.* ]]; then
            cond=true
        fi
    fi
    if [[ "$cond" == "false" ]]; then
        return 1
    fi
    local value="${arg%%=*}"
    if [[ "$value" =~ [[:space:]] ]]; then
        return 1
    fi
    return 0
}

_argc_die() {
    if [[ $# -eq 0 ]]; then
        cat
    else
        echo "$*" >&2
    fi
    exit 1
}

_argc_run "$@"

# ARGC-BUILD }

set -eu

# Validate --system flag if provided
if [ -n "${argc_system:-}" ]; then
    # List of supported systems from flake.nix
    SUPPORTED_SYSTEMS=("aarch64-linux" "x86_64-linux" "aarch64-darwin" "x86_64-darwin")

    # Check if the provided system is valid
    if [[ ! " ${SUPPORTED_SYSTEMS[@]} " =~ " ${argc_system} " ]]; then
        echo "Error: Unsupported system '${argc_system}'" >&2
        echo "Supported systems: ${SUPPORTED_SYSTEMS[*]}" >&2
        exit 1
    fi

    # Extract OS from target system
    target_os="${argc_system##*-}"

    # Get current system OS
    if [[ "$OSTYPE" == "darwin"* ]]; then
        current_os="darwin"
    else
        current_os="linux"
    fi

    # Warn if trying to cross-compile between different OSes
    if [[ "$target_os" != "$current_os" ]]; then
        echo "Error: Cross-compilation between different operating systems (${current_os} -> ${target_os}) is not supported by Nix" >&2
        echo "Please use a native builder for ${target_os} systems" >&2
        exit 1
    fi
fi

if [[ "$OSTYPE" == "darwin"* ]] && [ "${argc_no_root:-0}" -eq 1 ]; then
    echo "Error: --no-root is not supported on macOS"
    exit 1
fi

# Create config directory if it doesn't exist
mkdir -p config

# Save sudo mount preference to config file
if [ "${argc_sudo_mount:-0}" -eq 1 ]; then
    echo "SUDO_MOUNT_ENABLED=1" > config/shelffiles.conf
    echo "Sudo mount support enabled for containers"
else
    echo "SUDO_MOUNT_ENABLED=0" > config/shelffiles.conf
fi

# Use nix-portable when --no-root or --sudo-mount is specified
if [ "${argc_no_root:-0}" -eq 1 ] || [ "${argc_sudo_mount:-0}" -eq 1 ]; then
    if [ ! -e nix-portable ]; then
        echo "Installing nix-portable..."
        curl -L https://github.com/DavHau/nix-portable/releases/download/v012/nix-portable-"$(arch)" -o nix-portable
        chmod +x nix-portable
    fi
else
    if [ -e "$HOME"/.nix-profile/etc/profile.d/nix.sh ]; then
        # shellcheck disable=SC1091
        . "$HOME"/.nix-profile/etc/profile.d/nix.sh
    fi
    if ! command -v nix &> /dev/null; then
        echo "Installing Nix..."
        sh <(curl -L https://nixos.org/nix/install)
    fi
fi

echo "Building..."

# Determine the build target
if [ -n "${argc_system:-}" ]; then
    # Cross-compilation: use explicit system package
    BUILD_TARGET=".#packages.${argc_system}.default"
    echo "Cross-compiling for ${argc_system}..."
else
    # Default: use current system's default package
    BUILD_TARGET=""
fi

if [ "${argc_no_root:-0}" -eq 1 ] || [ "${argc_sudo_mount:-0}" -eq 1 ]; then
    ./nix-portable nix build --extra-experimental-features nix-command --extra-experimental-features flakes --store "$(pwd)" $BUILD_TARGET "${argc_nix_args[@]}"
else
    nix build --extra-experimental-features nix-command --extra-experimental-features flakes $BUILD_TARGET "${argc_nix_args[@]}"
fi

