#!/bin/sh

# Get the absolute path of the script directory
SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

# Source the environment setup
. "$SCRIPT_DIR/env.sh"

# Execute fish
if [ ! -e "$SHELFFILES/result" ] && [ ! -e "$SHELFFILES/result_docker" ] ; then
    exec "$SCRIPT_DIR/launch_in_bwrap.sh" fish "$@"
fi
exec fish "$@"
