#!/bin/sh

# Get the absolute path of the script directory
SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

# Source the environment setup
. "$SCRIPT_DIR/env.sh"

# Execute fish
exec fish "$@"
