#!/bin/sh

# Get the absolute path of the script directory
SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
SHELFFILES="$(CDPATH='' cd -- "$SCRIPT_DIR/.." && pwd)"
export SHELFFILES="$SHELFFILES"

# Source the environment setup
. "$SCRIPT_DIR/env.sh"

# Set ZDOTDIR if not already set
[ -z "$ZDOTDIR" ] && export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Workaround for vscode shell integration
export USER_ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Execute zsh
if [ ! -e "$SHELFFILES/result" ]; then
    exec "$SCRIPT_DIR/launch_in_bwrap.sh" zsh "$@"
fi
exec zsh "$@"
