#!/bin/sh

# Get the absolute path of the script directory
SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
SHELFFILES="$(CDPATH='' cd -- "$SCRIPT_DIR/.." && pwd)"
export SHELFFILES="$SHELFFILES"

# Source the environment setup
. "$SCRIPT_DIR/env.sh"

# Execute zsh
if [ ! -e "$SHELFFILES/result" ] && [ ! -e "$SHELFFILES/result_docker" ] ; then
    exec "$SCRIPT_DIR/launch_in_bwrap.sh" zsh "$@"
fi
exec zsh "$@"
