name: Lint Code with pre-commit

on:
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    name: runner / pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run pre-commit hooks
        run: |
          nix-shell -p pre-commit nixfmt --run "pre-commit run --all-files"
