name: Lint Code with pre-commit

on:
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    name: runner / pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
